name: sociall_syncup in Action

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout sociall_syncup repository
        uses: actions/checkout@v3

      - name: Setting python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setting environmental variables and executing
        env:
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_GROUP_NAME: ${{ secrets.TELEGRAM_GROUP_NAME }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SOURCE: ${{ secrets.SOURCE }}
          TARGET: ${{ secrets.TARGET }}
        run: python start.py
